### ISSUE TITLE
Qualification report: Time profile referenced in the report not saved

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1057]
When creating the qualification report from [4mail.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/11614483/4mail.zip) (which is part of DDI-CYP3A4 quali report)
I got the warning below:
```
! Warning	In createQualificationReport:
File(s): 'C:/re_output/images/032_section_3/054_section_322/comparison_time_profile_Bj%C3%B6rkhem_Bergman_2013_77.png' do not exist.
```

Indeed, the file is referenced in the report but is missing on disk.

From the log-debug file I also figured out that the warnings from #1056 also come from this problematic plot
[log-debug.txt](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/11614513/log-debug.txt)

**Comment by pchelle** [comment]
The issue is actually the file name here: `comparison_time_profile_Björkhem_Bergman_2013_1.png` 
The letter `ö` is not spotted as a special character by `removeForbiddenLetters` 
Thus, it appears in the actual file name but is translated as `%C3%B6` for ensuring display in `![](file/path)` of the markdown.
The issue appears when trying to copy the md report to another directory.

**Comment by pchelle** [comment]
The best solution is to convert such characters within `removeForbiddenLetters()` using `iconv()`
