### ISSUE TITLE
Tables in qualification reports: turn off the scientific notation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1183]
Compare the report https://github.com/Yuri05/TestReport/blob/main/Report_15_DDI_CYP3A4/report.md#2
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/25061876/5e1b7f76-0b9b-499e-9d46-fd6c83d27760)

**Comment by pchelle** [comment]
@Yuri05 
I think I was able to troubleshoot. However, the bug is affecting a lot more than just these tables.

I was expecting the behaviour of `reEnv` and `tlfEnv` to be reset when using `library`. 
But it is actually not the case... 
Thus, if you ran tests of the package, the scientific notation is triggered in `testthat/test-global-settings` but not reset to false after the tests. So, running a workflow after that keeps the scientific notation.

It seems the caps on the plots come from the same issue: if you tested `{tlf}` or `{ospsuite}` (that set the cap size to 5), it is likely the value was kept in the workflow.

**Comment by pchelle** [comment]
Here is an example:

``` r
library(ospsuite.reportingengine)
#> Loading required package: ospsuite
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000
#> Loading required package: tlf

ospsuite.reportingengine:::reEnv$formatNumericsScientific
#> [1] NA

setDefaultNumericFormat(scientific = TRUE)
ospsuite.reportingengine:::reEnv$formatNumericsScientific
#> [1] TRUE

library(ospsuite.reportingengine)

ospsuite.reportingengine:::reEnv$formatNumericsScientific
#> [1] TRUE
```

<sup>Created on 2024-02-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by pchelle** [comment]
Should we reset the `reEnv` onLoad ?
