### ISSUE TITLE
CL unit in PKRatio qualification plots

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1242]
@Yuri05 
while running the tests for qualification workflows, I encountered the error below 
```r
Unit 'l/h' is not included in available units for dimension: 'Flow per weight'.
```

the error comes from a difference between 
- the default unit of __CL__ defined in the Reporting Engine __'l/h'__ is a Flow
- the PK parameter unit of __CL__ from `{ospsuite}` is a Flow per weight 

``` r
ospsuite::pkParameterByName("CL")
#> PKParameter: 
#>    Name: CL 
#>    DisplayName: Total body clearance/F 
#>    Dimension: Flow per weight 
#>    DisplayUnit: ml/min/kg
```

<sup>Created on 2024-07-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Since the display name and unit from `{ospsuite}` are confusing (the word "total" is misleading), 
Can you let me know if I should fix the Reporting Engine CL as a Flow per weight ?

**Comment by Yuri05** [comment]
You mean this I guess:
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/e8a9ccaf75a02c0bf48a2a5067de9d4d8d7a42db/R/utilities-task.R#L1080-L1083

I am surprised that the CL unit is defined this way, especially because CL was already used in many qualification reports and the output was always in e.g. [ml/min/kg] (e.g. compare https://github.com/Open-Systems-Pharmacology/OSP-Qualification-Reports/blob/master/Pediatric_Qualification_Package_GFR_Ontogeny/report.md#evaluation-of-pediatric-translation).

So yes, please change the dimension to flow per weight and set the unit to **ml/min/kg**
