### ISSUE TITLE
Cannot set dimension of user defined PK-Parameter

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#192]
```
> F_tend <- ospsuite::addUserDefinedPKParameter(name = "F_tend", standardPKParameter = StandardPKParameter$C_trough, displayUnit = "%")
> F_tend$dimension = "Fraction"
Error: Property '$Dimension' is readonly
>
```

**Comment by msevestre** [comment]
This is not how it's supposed to work.
Dimension is read-only as the message says
As a user, you need to set the display units in this case, this will look to see if we have a dimension with this unit' if yes, it will use it. Otherwise it will create a dynamic dimension with only one unit and assume display unit = core unit

No changes required here

**Comment by Yuri05** [comment]
ok, then there is a bug somewhere else, because "_As a user, you need to set the display units in this case, this will look to see if we have a dimension with this unit' if yes, it will use it._" does not work.
Will create another issue for that.

**Comment by Yuri05** [comment]
So the first problem is: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/380

**Comment by Yuri05** [comment]
And the second problem: https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/193 (might be a follow-up problem of the first one)

**Comment by msevestre** [comment]
closing in favor of issue in core
