### ISSUE TITLE
Crash in Individual Sensitivity Analysis

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#214]
Execute `Workflow.R` from the example attached [bug01.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4740657/bug01.zip)
```
Error in grid.Call.graphics(C_setviewport, vp, TRUE) : 
  non-finite location and/or size for viewport
```

Note: sensitivity values do not correspond to the pkml model attached, because I had to replace the original model file with a dummy due to privacy reasons. Workflow.R just uses precalculated sensitivity values for plotting

**Comment by pchelle** [comment]
The problem is that some of the pk parameters are not output by the sensitivity analysis.
I was expecting that `ospsuite::allPKParameterNames()` and `sensitivityAnalysisResults$allPKParameterNames` would match but they don't.
@msevestre , is there a setting in the SensitivityAnalysis object or the run options to change that ?
I think the sa results and `allPKParameterNames` should match as default.

**Comment by msevestre** [comment]
> I think the sa results and allPKParameterNames should match as default.

No that does not make sense: `ospsuite::allPKParameterNames()` returns the list of all potential PK Parameter that may be available in the simulation. However, some are mutually exclusive (e.g. AUC_tEnd is only for single dosing and AUC_tD1_tD2 is only for multiple dosing)

Therefore, `sensitivityAnalysisResults$allPKParameterNames` returns the list of all PK Parameters defined for the simulation (and therefore for the SA).
