### ISSUE TITLE
Some error them ploting PK Parameters for population WF

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#241]
When executing the attached Workflow to plot the allready computed results, the following error occurs
Error in aggregate.data.frame(yValuesCol, xGroupingCols, function(x) { : 
  no rows to aggregate
[Rifampicin.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4790929/Rifampicin.zip)

**Comment by pchelle** [comment]
The issue comes from the PKAnalysis output file that does not includes the fraction excreted path requested in `outUrine`.
(The Simulation and PK parameter tasks need to be re-run for these to include the corresponding output path and pk parameters).
In PR #262 , I have added checking methods that will indicate a more appropriate error message for this type of error.

**Comment by Yuri05** [comment]
@ThomasGaub FYI attached example is invalid and will crash if executed AS IS. Simulation results / Sensitivity results /PK Results  contain only results for PeripheralVenousBlood but not for Urine. All calculation tasks ("populationSensitivityAnalysis","populationPKParameters","simulatePopulation") must be redone before plotting.
