### ISSUE TITLE
No Observed Data in TimeSeries plots / no residuals computed

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#253]
[Test_NO7.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4851434/Test_NO7.zip)

When performing attached workflow, something is wrong with observed data. The Observed Data is not plotted and no residuals are computed. 
Error Message is not helpfull.
Fehler in `[.data.frame`(data, , dataMapping$x) : 
  nicht definierte Spalten gewählt
Zusätzlich: Warnmeldungen:
1: Paket ‘ospsuite’ wurde unter R Version 3.6.3 erstellt 
2: Paket ‘rClr’ wurde unter R Version 3.5.2 erstellt 
3: Transformation introduced infinite values in continuous y-axis 
4: Transformation introduced infinite values in continuous y-axis 
5: Transformation introduced infinite values in continuous y-axis 
6: Transformation introduced infinite values in continuous y-axis

**Comment by Yuri05** [comment]
@ThomasGaub It seems that the data file has wrong format. Compare the "Matlab"-test case:
https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/develop/test/test_NO7/Input/data.mndat

**Comment by ThomasGaub** [comment]
Expected something like this, but tried readObservedDataFile and this seems to work fine. A more specific error message would be help full

**Comment by Yuri05** [comment]
ok, I looked into the wrong file. Data file seems ok to me, so maybe a bug indeed...

**Comment by pchelle** [comment]
The bug is related to the default "filtering" of observed data in `Output$new()` which does not select any data if the field is left empty for the goodness of fit. Actually, there should not be any residuals in this case (the bug should be fixed by PR #260 when it will pass the appveyor tests).
In this PR, we have tried to clarify the logic of the data filtering: 
* In `Output$new()`, the field `dataFilter` is replaced by `dataSelection`
* The default value is `dataSelection` = "NONE" (there won't be any observed data in the goodness of fit plot)
* To select all the observed data, `dataSelection` = "ALL" can be used
* If not sure of the actual data selection keys, the list `DataSelectionKeys` is exported and can be used (e.g. `DataSelectionKeys$NONE`)
