### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#271]
Every workflow should become a new string property `Watermark`.
* property should be NULL per default and can be overwritten by user
* if `workflow$Watermark` is set to a **non-empty** string: all workflow plots must be produced with this watermark 
* if `workflow$Watermark` is set to the **empty** string: no watermarks in all workflow plots
* if `workflow$Watermark` is NULL (the default case)
  * if the system is **validated**: no watermark in all workflow plots
  * if the system is **non-validated**: watermark „**preliminary analysis**” is created in all workflow plot

System is validated when the environment variable `VALIDATEDR_ENVIRONMENT` is defined and has the value `prodrun`

**Comment by Yuri05** [comment]
@thomasgaub FYI

**Comment by Yuri05** [comment]
@pchelle 
Does not work as expected if the user overrides default watermark:
* when setting `workflow$watermark = ""` no watermark must be produced (no matter if the system is validated or not)
* when setting `workflow$watermark = "My watermark"`: "_My watermark_" must be inserted as watermark

Currently in both cases the default watermark "_Preliminary analysis_" is inserted on a non-validated system

**Comment by pchelle** [comment]
@Yuri05 
To troubleshoot the problem, can you let me know if the problem is only in the plot (ie  does`workflow$watermark` provides the correct value or not) and how you set the watermark (as an input parameter of the worklfow `MeanModelWorkflow$new(..., watermark = "My Watermark")` or afterward `workflow$watermark <- "My Watermark"`) ?

**Comment by Yuri05** [comment]
I set it as property before run, e.g.

```
popModelWF <- PopulationWorkflow$new(simulationSets = list(popModelSet),workflowFolder = outputDir)
popModelWF$activateTasks(c("simulatePopulation","plotGoF","populationPKParameters","plotPKParameters","plotDemography"))
popModelWF$watermark="My Watermark";
popModelWF$runWorkflow()
```

And yes, the problem is onlyin the plot, if I query "`popModelWF$watermark`" once the workflow run is finished, it returns the correct value.

**Comment by pchelle** [comment]
So far, the method setting the watermark from the field `watermark` is only called in `$new()`.
That's why it is not printed on the plots.
I will set the `watermark` field as private to prevent this and add a `get/setWatermark` as a workflow function, if that's okay.
So, the previous line will translate as: `popModelWF$setWatermark("My Watermark")`

**Comment by Yuri05** [comment]
ok

**Comment by Yuri05** [comment]
@pchelle still does not work with user-defined watermarks. 
In both cases below I get the default "preliminary analysis" watermark in the plots on a non-validated system.

```
...
meanModelWorkflow <- MeanModelWorkflow$new(simulationSets = list(simulationSet1), workflowFolder = outputDir)
...
meanModelWorkflow$setWatermark("MyWatermark")
meanModelWorkflow$runWorkflow()
```

```
...
meanModelWorkflow <- MeanModelWorkflow$new(simulationSets = list(simulationSet1), workflowFolder = outputDir)
...
meanModelWorkflow$setWatermark("")
meanModelWorkflow$runWorkflow()
```
