### ISSUE TITLE
Missing Residuals for t=0

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#305]
No Residuals are displayed in plot or csv for time =0 

see attached Example

[Test_NO7.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5083540/Test_NO7.zip)

**Comment by pchelle** [comment]
I checked the example, 
The simulated value and some observed values at time=0 are 0, since __residuals = log(Observed)-log(Simulated)__, R outputs __Inf__ or __-Inf__ values for residuals which can crash the plot. 
As a consequence, these values are transformed into missing values __NA__ and then all missing values are removed from the output plot and csv. Indeed, __NA__ values can also crash the plot in some cases (e.g. only NAs).

In the debug and error logs, it is indicated that such values were found and removed:
17/08/2020 - 08:05:37 : 3 values were infinite and transformed into missing values (NA)
17/08/2020 - 08:05:37 : 12 values were missing (NA) from variable 'Residuals' and removed from the analysis

Let me know if you want me to keep the __NA__ values in the .csv

**Comment by ThomasGaub** [comment]
In my Opinion we should keeo the NA in the CSV. 
Other Opinion @Yuri05

**Comment by sfrechen** [comment]
Agree with @ThomasGaub

**Comment by ThomasGaub** [comment]
Still no entries for t= 0 in csv!

**Comment by msevestre** [comment]
@ThomasGaub Can you try with the latest version (make sure you update ReportingEngine). The error should be fixed

**Comment by msevestre** [comment]
see code in commit
https://github.com/pchelle/OSPSuite.ReportingEngine/commit/54fc707ceb6b9116b3928377c818418b581c5c74

![image](https://user-images.githubusercontent.com/1041237/92119592-074cc280-edc6-11ea-89b9-328589723516.png)

**Comment by ThomasGaub** [comment]
with 1.0.66 fixed
