### ISSUE TITLE
Watermark missing in the pie plots

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#308]
MEanmodel-workflow: watermark is missing in the mass balance pie plots
![grafik](https://user-images.githubusercontent.com/25061876/90779408-1891cb80-e2fe-11ea-872b-f6724a85f448.png)

**Comment by pchelle** [comment]
Yes, the problem is that adding watermarks relies on `ggplot2::annotation_custom()` which is not compatible with `ggplot2::coord_polar()` that needs to be called to create pie charts.
The only workaround I have found is to create a pie chart __grob__ (kind of a ggplot grid layer) which I can add as a plot layer to an empty tlf plot object which contains the watermark.
However, the watermark will encompass both plot and legend. Would this still be okay ?

This is what the result would look like:
![image](https://user-images.githubusercontent.com/45343665/91034755-832f5980-e5d3-11ea-8dd7-dce91e43f814.png)

**Comment by Yuri05** [comment]
@pchelle Yes, absolutely ok from my point of view
