### ISSUE TITLE
Ensure minimal tlf and ospsuite versions

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#336]

**Comment by pchelle** [comment]
@msevestre 
Trying to implement this feature, I got building fail because the version was 9.0.0 for the package `ospsuite`.
I noticed that the installed version used the information written in __DESCRIPTION__ and can be updated using `usethis::use_version()`.
I think we should update `tlf` and `ospsuite` versions in the description file so they match the value in the tag, thoughts ?

**Comment by msevestre** [comment]
@pchelle I am not quite sure I understand the problem
Is this because we dowlonad the file from github? I guess the issue is that we are updating the version at build time
Therefore, we might have to change strategy and say that we need to ensure that we are depending a X.Y version of a package (e.g. 1.1, 2.4 etc..) and not the build version that comes from appveyor

Does it make sense?

**Comment by pchelle** [comment]
Your strategy makes sense.

Would it be simpler to directly align both the version as written in the DESCRIPTION file and the version output by appveyor ?
So we don't need to bother where the package is loaded from.

**Comment by msevestre** [comment]
Ok maybe I misunderstand what you are saying
What DESCRIPTION file are you talking about?

This line here 
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/DESCRIPTION#L4

for example is changed at build time. There is no way to have if fixed since the version number changes changes everytime we build a new value

Now we can definitely say we can update the version to be higher but this will be potentially brittle

**Comment by pchelle** [comment]
Yes, I was talking about this very line.
It is not changed when we install the package using github, which leads to install a version 9.0.0 for ospsuite.
For tlf and reporting engine, version is 0.1.0

So, if I follow, a more robust way would be to have the artifact R bundle from the develop version installed ?

**Comment by msevestre** [comment]
What we could do for now is to make sure that we update those versions in
the namespace to what we have released officially.

But later we have to make sure that a breaking change also changes the
minor version => 1.1 to 1.2
