### ISSUE TITLE
Excel-Template generation: concatenation of dataSelection

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#361]
When concatenating dataSelection of a simulation set with the dataSelection of an Output: 
if one of dataSelections is set to "NONE" then the resulting dataSelection is just NONE (which is correct), e.g.

```
Outputs10mg.VenousBlood <- Output$new(path = "Organism|PeripheralVenousBlood|Raltegravir|Plasma (Peripheral Venous Blood)",
  displayName = "Raltegravir simulated data",   displayUnit = "mg/l",
  dataSelection = "NONE",
  dataDisplayName = "MySimset1 - Raltegravir observed data", pkParameters = pkParameters
)
```

But if one of dataSelections is set to "ALL" then resulting dataSelection is "TRUE & dataSelection2", e.g.
```
Outputs50mg.VenousBlood <- Output$new(path = "Organism|PeripheralVenousBlood|Raltegravir|Plasma (Peripheral Venous Blood)",
  displayName = "Raltegravir simulated data", displayUnit = "mg/l",
  dataSelection = 'TRUE & Grouping %in% "50mg"',
  dataDisplayName = "Raltegravir observed data", pkParameters = pkParameters
)

```

This is not wrong, however shouldn't we just generate `dataSelection ="Expression2"` instead of `dataSelection = "TRUE & Expression2"`?

**Comment by pchelle** [comment]
The issue with "ALL" is that if you select "ALL" in both concatenation levels, you do not want to remove both statements, because it will mean that you will select nothing.
I will add a few lines in the concatenation to check if "ALL" is found everywhere and assign a final unique "ALL" statement in that case and remove the statement otherwise.
