### ISSUE TITLE
Pop-Workflow: Error in calculate sensitivity

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#371]
When executing the workflow in [bug.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5512475/bug.zip) the error below comes:
```
[1] "09/11/2020 - 19:07:06 : Starting Perform sensitivity analysis task"
[1] "09/11/2020 - 19:07:06 : Run sensitivity for simulation: Larson 2013 8-18y meal"
Error in data.frame(Output = output, pkParameter = pkParameter, Quantile = quantileVec,  : 
  arguments imply differing number of rows: 1, 3, 0
```

Additional info: workflow was generated from [WorkflowInput.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5512480/WorkflowInput.xlsx) (and the error in #370 was manually fixed in the generated code)

**Comment by pchelle** [comment]
@Yuri05 , the error happens around line 450 of the file utilities-sensitivity-analysis:
the code tries to build a data.frame of the specific quantiles of pk parameter values, but for the MRT of the requested path there are only NaN/NA values causing the function `getQuantileIndividualIds` to return an empty vector instead of a vector of length 3.

@abdullahhamadeh , I am not sure of what we should be return in such a case, since the data.frame is used to map the individuals on which the sensitivity analysis is performed ?

**Comment by Yuri05** [comment]
MRT is **not** in the list of required PK parameters for the output, so why does RE try to calculate the sensitivity at all?

**Comment by abdullahhamadeh** [comment]
> MRT is not in the list of required PK parameters for the output, so why does RE try to calculate the sensitivity at all?

@Yuri05 in this example there are two simulation sets, each with two outputs.  The second output in each simulation set has no pk parameters defined.  The current default behavior in RE is that if no PK parameters are defined, the SA is conducted for ALL pk parameters that had previously been calculated.

> So before line 450 I would expect a check if PK-parameter is required for the output or not. If not: continue with the next PK-parameter.

Indeed this filtration does take place, a few lines earlier in the function `getPKResultsDataFrame`, but only for outputs for which pk parameters are specified.

The bug occurs because, as @pchelle wrote, NaN is returned for MRT for the output for which no pk parameters were set.  The bug can be fixed by skipping the SA for any pk parameters that return NaN (regardless of whether they were specified or not).  

But there is still the question of whether the default behavior should be that no SA is performed when no pk parameters are set.

**Comment by Yuri05** [comment]
>But there is still the question of whether the default behavior should be that no SA is performed when no pk parameters are set.

Yes. If no PK parameters were defined for an output then no SA should be performed.

>The bug can be fixed by skipping the SA for any pk parameters that return NaN (regardless of whether they were specified or not)

The question would be if in such a case SA should be skipped if ALL values of a PK-Parameter are NaN, or if not-NaN values are below predefined threshold... To be discussed. For now I would suggest just to skip the SA if no PK parameters are defined for the output.
