### ISSUE TITLE
Crash in PlotTimeProfiles-Task

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#450]
[26.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6216112/26.zip)
```
[1] "27/03/2021 - 18:52:05 : Plot Time profiles and Residuals task for SimSet_aaa"
Error in self$settings$referenceData <- taskResults$referenceData : 
  cannot add bindings to a locked environment
```
The reason could be that the dictionary is "old-style" (without units) - then missing units are not properly catched?
![grafik](https://user-images.githubusercontent.com/25061876/112729755-0f20af80-8f2e-11eb-8f54-58642aaf47d8.png)

**Comment by Yuri05** [comment]
nope, it's not because of the dictionary. If I fill missing unit - still the same error.
[tpDictionary.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6216127/tpDictionary.zip)

**Comment by pchelle** [comment]
The issue is that `settings` has become an R6 object since the last PR (application ranges) to allow help users manipulate the settings.
Since, I forgot that `referenceData` could be a settings (only used for population workflows in which there is a reference population), it is not declared yet as a potential field of the object.
I'll fix that ASAP
