### ISSUE TITLE
LLOQ line displayed as dots in the legend

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#478]
![grafik](https://user-images.githubusercontent.com/25061876/116568535-d8f99580-a908-11eb-94d4-0cc4550e7395.png)

**Comment by pchelle** [comment]
I tested on a dummy dataset the new lloq features from `{tlf}`,
- "LLOQ" is not displayed in the legend name anymore
- BLQ data points use higher transparency

<details><summary>Time profile plots would look like this</summary>

![A-3_timeProfile_Concentration_total](https://user-images.githubusercontent.com/45343665/236462036-bccc13e9-97b0-463c-ad52-35615441c9c5.png)

</details>

**Comment by pchelle** [comment]
Also, since the feature was also added to obs vs pred plots, I can spread the dotted lines to those:

<details><summary>Observed vs Predicted with LLOQ</summary>

![A-6_obsVsPredLog_Concentration_total](https://user-images.githubusercontent.com/45343665/236463440-210918af-68f5-4cb4-b95c-884e5964a570.png)

</details>

**Comment by Yuri05** [comment]
@pchelle 
>If you are okay with such plots, I can include in the figure caption of the report that "dotted line corresponds to LLOQ" or a similar text.

Yes, dotted LLOQ line looks better and yes, let's include the legend "LLOQ for `<caption of the observed data set>`"

>Also, since the feature was also added to obs vs pred plots, I can spread the dotted lines to those:

Yes, let's do it :)
