### ISSUE TITLE
List of qualification project to use for testing

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#525]

**Comment by Yuri05** [comment]
DDI: https://github.com/Open-Systems-Pharmacology/Qualification-DDI-UGT
PK-Ratio: https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_CYP3A4_Ontogeny

**Comment by Yuri05** [comment]
later: https://github.com/open-systems-pharmacology?q=%22osp-qualification%22&type=&language=&sort=

**Comment by pchelle** [comment]
[Report.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/7202063/Report.zip)

**Comment by pchelle** [comment]
@Yuri05 , I have tested the PK Ratio workflow and attached the current look of the report.
I have already noticed some things that may require separate issues below.
Let me know if you also find any odd things in the report.
- when creating the table of content, we are currently numbering the sections (do we need to add an option for including/not including the numbering)
- Make sure of what is wanted for section content (when title and content are both defined, we said we don't use title, but here title seemed wanted before the content)
- in the each table, the numeric format is using the reporting engine default which can be tuned using `setDefaultNumericFormat(digits, nsmall, scientific)`. Do we also want to include such input in the configuration plan ?
- PK Ratio Plot uses the value in the field title, however, this makes it weird for the tables. Let me know if other or new inputs/values are expected.
- Configuration plan defined default plot size as 500x400 pixels (and some specific plots as 400x400 and 600x400), let me know if it is consistent with the actual figure sizes of the report
- Population time profile plots are not ready yet
- A couple of time profile plots were not saved, I need to investigate what happened for those (only message was issue in the `ggplot2` saving mentioning that it could not open the png device (wondering if the file name was too long)

**Comment by Yuri05** [comment]
>when creating the table of content, we are currently numbering the sections (do we need to add an option for including/not including the numbering)

Don't see the need for this at the moment.

>Make sure of what is wanted for section content (when title and content are both defined, we said we don't use title, but here title seemed wanted before the content)
  
What we need: allow no content for a section, just a title. At the moment content is mandatory and users often create empty.md file as a workaround

> in the each table, the numeric format is using the reporting engine default which can be tuned using setDefaultNumericFormat(digits, nsmall, scientific). Do we also want to include such input in the configuration plan ?

Good idea, we could extend the plot settings and allow thus to define those settings both globally and locally

>PK Ratio Plot uses the value in the field title, however, this makes it weird for the tables. Let me know if other or new inputs/values are expected.

Not sure what you mean (maybe because I'm using my phone right now). Can you attach a screenshot?

>Configuration plan defined default plot size as 500x400 pixels (and some specific plots as 400x400 and 600x400), let me know if it is consistent with the actual figure sizes of the report

We need to experiment a bit to figure out the optimal size.
   
>A couple of time profile plots were not saved, I need to investigate what happened for those (only message was issue in the ggplot2 saving mentioning that it could not open the png device (wondering if the file name was too long)

Under Windows file paths longer than 255 chars are still a problem for some applications. RE could check every time before saving a file if the path is longer than 255 chars and if running under windows-show warning

**Comment by Yuri05** [comment]
Overall the report looking good!
There are some minor issues, but I need to watch it on a bigger monitor and not on the smartphone first before I create any issues:)

Could you also upload the markdown version of the report (e.g. in one of your repositories)?

**Comment by pchelle** [comment]
I copied the md version in one of my repo and noticed another bug regarding obs vs pred plots.

https://github.com/pchelle/Test-of-Pediatric-Qualification-Workflow/blob/7fed266cc7297e9f363d4edaec72952c62fdcaef/Report.md

**Comment by pchelle** [comment]
> Under Windows file paths longer than 255 chars are still a problem for some applications. RE could check every time before saving a file if the path is longer than 255 chars and if running under windows-show warning

I have tested `ggsave` with long strings and you are totally right.
In our case the file name is long because the folder and subfolder names of the relative paths are already long.
Should we also shorten the names of these folders on top of checking the path length when saving ?

Currently, when creating the folder structure, the section paths are defined as:
`sprintf("%0.3d_%s", sectionIndex, removeForbiddenLetters(section$Title))` which produces paths for plots such as
`"002_Chapter 2_ Pediatric translation qualification results/003_Chapter 2_1_ Sufentanil PK Ratio tables and Figures/7-pk-ratio-plot-AUC.png"`.
@Yuri05 , let me know if you would like me to add a character cut-off for these section folder names as well.

**Comment by pchelle** [comment]
> What we need: allow no content for a section, just a title. At the moment content is mandatory and users often create empty.md file as a workaround

Since R and jsonlite are more flexible than Matlab, the function `sectionsAsDataFrame` check only if `Id` and `Title` are provided by users (which currently makes only these 2 mandatory, `Title` is re-used for the naming of the markdown appendices and folders where plots and tables are saved).

Then, the function `createSectionOutput(configurationPlan)` creates one markdown file per section/subsection.
Each markdown is currently either filled by `Content` (if defined) or by `Title` (if not defined).

**Comment by abdullahhamadeh** [comment]
I'm having trouble with the qualification runner for Qualification-DDI-UGT:

```
info: QualificationRunner[0]
      Starting qualification workflow
fail: QualificationRunner[0]
      The remote server returned an error: (404) Not Found.
fail: QualificationRunner[0]
      Observed data file 'https://raw.githubusercontent.com/Open-Systems-Pharmacology/Database-for-observed-data/v1.3/DDI.csv' does not exist.
fail: QualificationRunner[0]
      Qualification Workflow failed
```

Have the files moved?

**Comment by msevestre** [comment]
https://raw.githubusercontent.com/Open-Systems-Pharmacology/Database-for-observed-data/v1.2/DDI.csv

does exist

but v1.3 not

**Comment by Yuri05** [comment]
@abdullahhamadeh Update: v1.3 was released today, so you should be able to use the qualification plan AS IS

**Comment by pchelle** [comment]
Current version of the pediatric report run using the PR from yesterday:
https://github.com/pchelle/Test-of-Pediatric-Qualification-Workflow/blob/main/Report.md

**Comment by Yuri05** [comment]
@pchelle The report seems to be created with an older version of the qualification plan, which makes it harder to compare with the last Matlab-generated report. Could you recreate the report with the [current state of the qualification repository](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_CYP3A4_Ontogeny)?

**Comment by Yuri05** [comment]
@pchelle Did you have a chance to create this report with the latest version of the qualification plan?

**Comment by pchelle** [comment]
@Yuri05 
I just updated the report with the latest version:
https://github.com/pchelle/Test-of-Pediatric-Qualification-Workflow/blob/main/Report.md

**Comment by pchelle** [comment]
Also, I tested the template to try this out and got 3 issues:
- `startQualificationRunner` did not work on my laptop because the .exe of the Qualification Runner was within quotes (removing the quotes in the command line solved it)
- the qualification runner adds `.json` to the configuration plan file which ends up as `.json.json`. 
Do we want the template to account for that or do we want the runner to use the configuration plan file as is ?
- Time profile task breaks because some of the plots end ups with no axes settings at all (we don't know the unit and dimension of the values to plot there - to fix that I copied the content of `Plots$AxesSettings$ComparisonTimeProfile` in a field named `Plots$AxesSettings$TimeProfile`)
