### ISSUE TITLE
Replace confusing observed data terminology nonmenColumn and nonmemUnit by datasetColumn and datasetUnit

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#534]
The terminology is confusing. NONMEM is a proprietary software tool and stands for non-linear mixed effects modelling. First, it has nothing to do with data.

Please replace throughout the ReportingEngine:
`nonmenColumn` --> `datasetColumn`
`nonmemUnit` --> `datasetUnit`

(And yes, it is not a typo by me... it is currently written as "nonme**n**Column"...)

Affected files (no warranty for completeness):
- error-checks.R
- messages.R
- uitilities-observed-data.R
- Excel Template (WorkflowInput.xlsx) -> Sheet "tpDictionary"

@Yuri05 @Christoph27 @AnnikaRPS

**Comment by Yuri05** [comment]
@sfrechen do we need backward compatibility in the dictionaries? I mean: if the new column name is not found: should RE try to find the old column name?
E.g. if the "datasetUnit" column is missing: should RE look for the "nonmemUnit" column?
If yes: data dictionaries in existing RE workflows can be kept AS IS. Otherwise existing datadictionaries need to be adjusted for the new naming.

**Comment by sfrechen** [comment]
I don't have any RE workflows for R ReportingEngine :-).
But I would guess if we fix it soon... there is virtually no impact since it hasn't been used in a productive way too often.
And to **_reproduce_** old results (if there are one), one needs to use anyway the corresponding ReportingEngine version.

Thus: I would say: **_no_** backward compatibility needed.

**Comment by msevestre** [comment]
>Thus: I would say: no backward compatibility needed.

WOOT WOOT!!
