### ISSUE TITLE
Chapters messed up

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#595]
Based on https://github.com/pchelle/Test-of-Pediatric-Qualification-Workflow/blob/main/Report.md
grafik
In the qualification plan the chapters are defined as below:
![grafik](https://user-images.githubusercontent.com/25061876/141526889-342770e9-a88b-4fce-a94e-71662206c9e4.png)

Thus I would expect those chapters to appear in the report (and this is how it looks like in the report generated with the Matlab RE):
![grafik](https://user-images.githubusercontent.com/25061876/141527159-407fde9d-46b2-4ee5-b861-6532baf06d1b.png)

But now it looks like this:
![grafik](https://user-images.githubusercontent.com/25061876/141527246-a5abf824-9611-4599-991c-c0df8f466a55.png)

**Comment by pchelle** [comment]
This bug is the results of two things:
1* If Content and Title are defined, only Content is used (https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/525#issuecomment-925790781)
2* We do not have an option to keep/remove the numbering of the sections (which is kept by default)

@Yuri05 , can you let me know what is expected for both points above ?

**Comment by Yuri05** [comment]
Keep the title and introduce the "remove numbering" option (which should be true for qualification reports by default)
