### ISSUE TITLE
Missing plots

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#605]
Based on https://github.com/pchelle/Test-of-Pediatric-Qualification-Workflow/blob/main/Report.md

2 last plots are missing in the report - compare Matlab report:
![grafik](https://user-images.githubusercontent.com/25061876/141600538-442e4557-bb57-4311-b668-878bd6c2c385.png)

**Comment by pchelle** [comment]
The population file was not output by the qualification runner.
I thought I had the right versions, don't I ? (QualificationRunner10.0.55 and PK-Sim10.0.251)

**Comment by Yuri05** [comment]
The latest versions are:
* PK-Sim: either installed with the OSP 10 or (if using the portable version) version 10.0.257 https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/tag/v10.0.257
* Qulification Runner 10.0.59: https://github.com/Open-Systems-Pharmacology/QualificationRunner/releases/tag/v10.0.59

Please check if you still the problem with the latest versions

**Comment by pchelle** [comment]
@Yuri05 
The correct version of the Qualification Runner worked but the population time profiles are currently not run.
The reason is that I am currently throwing a *warning* and skip the plot if its Axes Properties are not defined 
(btw, let me know if this should be an *error* instead).
I had hoped that Population time profiles had a similar definition of axes compared to other plots, but it is not the case:

* All plot but time profiles use global and local `AxesSettings` fields
* Mean time profiles can override the global  `AxesSettings` field with local `Axes` field 
(which always happens since I have never seen any global axes setting for time profile) 
* However, Population time profiles have only partial information for such properties: 
the field `Fields` from the field `Analysis` provides a unit and a scaling for y axis, but there is nothing defining the x axis... 

Would it be possible to export the axes settings for population time profiles the same way as they are done for mean time profiles ?

**Comment by Yuri05** [comment]
>Would it be possible to export the axes settings for population time profiles the same way as they are done for mean time profiles ?

The problem is that those settings currently cannot be defined in PK-Sim at all for pop simulations:
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1546
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1547

So fixing might be a bigger effort. Can you take for the population plots the global time profile axes settings and overwrite only those axis settings which are found in the configuration of a population plot?

**Comment by pchelle** [comment]
> Can you take for the population plots the global time profile axes settings and overwrite only those axis settings which are found in the configuration of a population plot?

I can but I haven't seen any global axes settings for time profile. 
So currently, for the pediatric example, the config plan does not provide the unit, dimension or scale for the x axis.

**Comment by Yuri05** [comment]
>I can but I haven't seen any global axes settings for time profile.

True... 
We could introduce TimeProfile axes settings then. However I would make them optional, otherwise all current qualification plans would become invalid and must be adjusted. So I would suggest (to be discussed):
* If the global TimeProfile axes settings are present - take them
* If not:
  * Option 1: take the **Comparison**TimePofile global axes settings instead
  * Option 2: use predefined defaults (e.g. unit=[h], Scaling=Lin for the X-axis etc,)

How did actually the Matla-RE deal with this situation?

**Comment by pchelle** [comment]
> How did actually the Matlab-RE deal with this situation?

Option 2 was used then in [runQualificationWorkflow.m](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/dbbad2ee151041f743ae12e38d9229548b3ebf68/src/code/qualification/runQualificationWorkflow.m#L72)

**Comment by GhazalMontaseri** [comment]
I tried to generate the qualification report for Fluconazole model based on files provided here:
https://github.com/Open-Systems-Pharmacology/Fluconazole-Model

However, instead of Workflow.m I have used workflow.R as described here:
https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/articles/qualification-workflow.html#template

I have PK-Sim portable version 11 and latest version of 'QualificationRunner'. The issue is in concentration-time profiles with double Y axes like Y and Y2 (like the third plot in section 3.3.1),  I got a plot with only Y and not both Y and Y2. Can you please help me with this issue?
