### ISSUE TITLE
Parameters to be varied in SA: set in SA task or simulationSet?

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#63]
Currently set in the SA task.  However, if there are multiple simulationSets to be run, each with a different model, then some of the parameters to be varied in one model may not exist in the other. 
 I have added an error check to stop the workflow when this happens, but this problem goes away if we specify the variable parameters in the simulationSet.  But this is less elegant since variable parameters are associated with the task instance, not so much the simulationSet.

**Comment by msevestre** [comment]
@abdullahhamadeh This should only be an issue if the user **specifies** a list of parameters to vary correct?
Otherwise the system should vary automatically all parameters potentially variables in a simulation. Am I right?

In that case, throwing an error is ok as the user as constructed a scenario that does not make sense.

**Comment by abdullahhamadeh** [comment]
ok the latest pull request has the error check

**Comment by Yuri05** [comment]
This issue can be closed now, correct?

**Comment by Yuri05** [comment]
Closing. Please reopen if there is still a to do
