### ISSUE TITLE
Test fails locally

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#697]
I installed the package compiled in the PR [Apply runSimulations of sequence of subsets of structureSets](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/677)
In the PR, all test that tests succeeded on AppVeyor. However locally 1 test failed. Any idea why?
(Other package versions: tlf - **1.2.41**, ospsuite - **11.0.47**, ospsuite.utils: **1.1.0**)

```
-- Error (test-qualification.R:12:1): (code run outside of `test_that()`) ---------------------------
Error: In source:
'Mini' is not included in 'project' variable of simulationMappings.
Backtrace:
    x
 1. \-ospsuite.reportingengine::loadQualificationWorkflow(...) test-qualification.R:12:0
 2.   \-QualificationWorkflow$new(...)
 3.     \-ospsuite.reportingengine:::initialize(...)
 4.       \-ospsuite.reportingengine::loadQualificationTimeProfilesTask(...)
 5.         \-base::sapply(...)
 6.           \-base::lapply(X = X, FUN = FUN, ...)
 7.             \-ospsuite.reportingengine:::FUN(X[[i]], ...)
 8.               \-configurationPlan$getSimulationResultsPath(...)
 9.                 \-ospsuite.reportingengine:::validateIsIncludedAndLog(...)

[ FAIL 1 | WARN 57 | SKIP 0 | PASS 336 ]
```

**Comment by pchelle** [comment]
@Yuri05 
I was able to reproduce the issue since I got it in the last PR I made.
If I get it right, the update of `ospsuite.utils` changed the behavior of the function `isIncluded` regarding character and factor classes: `"Mini"` is actually a factor class in that failed test and simulationMappings$project is character.

Btw, I don't know if the updated behavior is what is expected for these classes:
```r
isIncluded(as.factor("A"), as.character("A"))
> FALSE

isIncluded(as.character("A"), as.factor("A"))
> TRUE
```

**Comment by Yuri05** [comment]
>Btw, I don't know if the updated behavior is what is expected for these classes:

I have no idea... @IndrajeetPatil @msevestre

**Comment by msevestre** [comment]
Oh my...please tag Indra here. 
I wish we would habe had tests for this.

**Comment by msevestre** [comment]
What are you trying to do Pierre? Check if a factor is in a list of string?

**Comment by IndrajeetPatil** [comment]
Yikes. This is definitely a regression in `ospsuite.utils`. We wanted to avoid users using this function to check objects, but, turns out factors are objects 👀 

``` r
library(ospsuite.utils)

x <- as.factor("A")
y <- as.character("A")

isIncluded(x, y)
#> Error: Only vectors of base object types are allowed.

is.object(x)
#> [1] TRUE
```

<sup>Created on 2022-02-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I will see what we can do to fix this and, if necessary, make a hotfix release on CRAN.

**Comment by IndrajeetPatil** [comment]
Tracking this here: https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/issues/63

**Comment by pchelle** [comment]
> What are you trying to do Pierre? Check if a factor is in a list of string?

At the beginning, I was just troubleshooting the reporting engine issue and noticed that isIncluded returns true for a character included in a factor class object but not the opposite. I was just wondering what was the intended behavior of the function.
