### ISSUE TITLE
Vignettes: fixed width?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#711]
Currently the width of the vignettes is somehow fixed. Is it possible to change this and make vignettes width adjustable to the width of the browser window? Even with the small resolution it looks like in the screen below.
Also some tables are displayed not optimally (s. below)
https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/dev/articles/introduction-re-instances.html#nomenclature

![grafik](https://user-images.githubusercontent.com/25061876/155296703-0261ec05-b33c-49b4-9cb7-1c1d31842045.png)

**Comment by pchelle** [comment]
I think this might be related to the css file that we implemented to highlight results of workflow examples because the vignette related to the Qualification Workflow does not have issue with vignette width https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/dev/articles/qualification-workflow.html

**Comment by pchelle** [comment]
@Yuri05 
Actually, the issue is caused by `htmltools::includeHTML` used when we include the workflow reports. The function is changing the styling of the vignette somehow).
Now that I have a better knowledge of rmarkdown, I can replace that function by `knitr::raw_html(readLines())` with the option `result='asis'` that will work the same, without changing the vignette styling - keeping the correct width.

**Comment by Yuri05** [comment]
sounds good

**Comment by Yuri05** [comment]
still an issue. reopening...

**Comment by pchelle** [comment]
PR #917 fixed this.
But let's keep it open until all the documentation is updated
