### ISSUE TITLE
Error in validateIsOfType

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#732]
Running the example attached [Input.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/8286311/Input.zip) (small subset of CYP3A4-DDI qualification workflow)
produces the error
```
[1] "17/03/2022 - 14:13:24 : Starting: Plot Comparison Time Profiles task"
Error in validateIsOfType(quantityOrDimension, c("Quantity", "character")) : 
  createQualificationReport: argument 'quantityOrDimension' is of type 'NULL', but expected 'Quantity, or character'!
```

ospsuite: 11.0.70
ospsuite.reportingengine: 2.0.143
ospsuite.utils: 1.2.0
tlf: 1.2.44

**Comment by abdullahhamadeh** [comment]
@Yuri05 , this is failing because it is unclear what the units should be for Var in this data file:
![image](https://user-images.githubusercontent.com/18409098/158889769-9d679697-1438-45c6-b52e-e40636b16378.png)

Should we take it as dimensionless?  It seems like a geometric uncertainty (Var entries >> Avg entries).

Are the units missing by mistake, or is this a scenario we should handle?  i.e. should it throw an error that reports the missing units, or should this be taken as dimensionless geometric uncertainty wrt the Avg column and handled accordingly?

**Comment by Yuri05** [comment]
Yes, no units = "dimensionless", and in 99.9% it will be geometric error.
The only case where it's ambiguous: dimensionless measurement and dimensionless error.
E.g. measurement = fraction without unit.

So I would suggest:
* Error column has unit ==> arithmetic error with the given unit
* Error column has no unit ==> Check if all nonempty values are >=1
  * If this is the case => Geometric error
  * If this is not the case
    * If measurement has no unit as well ==> Arithmetic error; both measurement and error are set dimensionless
    * Otherwise (measurement has unit): throw error (inconsistent data)

P.S. how was it done in the Matlab RE?

**Comment by pchelle** [comment]
This was partly done this way in both Matlab and R Reporting Engines (the check of values > 1 has not been implemented).

**Comment by pchelle** [comment]
Here, the error happens because the behaviour of the function `separateVariableFromUnit` is not what I was expecting.
If no unit I was expecting either `NULL` or "" but instead get the name of the variable

```r
> separateVariableFromUnit("Time [h]")
$name
[1] "Time"

$unit
[1] "h"
```

but 
```r
> separateVariableFromUnit("Var")
$name
[1] "Var"

$unit
[1] "Var"
```
