### ISSUE TITLE
Word report: text body should not be bold

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#748]
Most of the text is currently "bold":

![image](https://user-images.githubusercontent.com/25903040/161032289-1cee29e7-220c-4207-98cb-bdfe38a523f9.png)

vs

![image](https://user-images.githubusercontent.com/25903040/161032299-5cad4709-7be0-4f55-9de5-296e6d9817ae.png)

**Comment by Yuri05** [comment]
Conversion MD=>DOCX is done via Pandoc; most of the Word formatting options are triggered by the **conversion template** word file, which is passed to Pandoc.
Currently RE is using the [conversion template file](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/develop/inst/extdata/reference.docx) which was adjusted to our needs for non-qualification workflows (MeanModel-/Population-Workflow) and we need to keep it AS IS.
What we could do: extend qualification workflow start function with an optional argument (path to user supplied conversion template) and then create **another** template (or even different templates) for qualification workflows, which could be then optionally passed to the qualification workflow.
Then users could even create their own conversion templates (which is however not straight forward).

If you like, you can create a new conversion template by:
* opening the current [conversion template file](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/develop/inst/extdata/reference.docx)
* adjusting the properties of different elements (text, figure captions, TOC etc.). 
**Important**: you need to adjust the properties of those elements not directly in the document, but **in the styles**
<br><br>
![grafik](https://user-images.githubusercontent.com/25061876/161040992-c067fd6c-b560-4d92-b22a-2f4c898ed443.png)
<br><br>
* Save the document.
**Important**: do NOT upgrade the document version while saving, otherwise the Pandoc conversion will crash.

**Comment by Yuri05** [comment]
Fixed by https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/965
