### ISSUE TITLE
Debug log file: strange entries

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#79]
![grafik](https://user-images.githubusercontent.com/25061876/76748108-7bdd6780-677a-11ea-8097-aa76f82bebc4.png)

**Comment by abdullahhamadeh** [comment]
These should look like this now:
![image](https://user-images.githubusercontent.com/18409098/76783600-90c0f780-6788-11ea-963e-3dae434ad1e5.png)
Taking, eg, line 24: the second time point is when the activity occurred on the core.  The first time point (occurs later) is when the log from the core was added to the log on the master.

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/76784221-a2ef6580-6789-11ea-84e1-966ceceac462.png)

I don't get this
Why do you start by path? The output care calculated for all paths at once. 
e.g for one parameter value, you get the SA for ALL paths. maybe that's why it takes so much more time?

**Comment by abdullahhamadeh** [comment]
The idea is :
1 - we pick an individual on whom to perform sensitivity analysis because they correspond to a quantile of a pk parameter distribution that we are interested in.
2 - If there are N variation parameters and c cores, each core handles N/c cores for that individual.  

So in this example there are only four perturbation parameters and four cores.  If there were 80 perturbation parameters there would be 20 on each core.

**Comment by msevestre** [comment]
What I don't understand is the nuance by "path". The sensitivity should be split by parameter not by path

**Comment by msevestre** [comment]
oh it's path of the parameter not of the output

**Comment by msevestre** [comment]
ok all good then. I still don't understand why a pop simulation should be order of magnitudes faster
