### ISSUE TITLE
How do I reference tables and content with the anchor?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#798]
Can I get an example here 
See https://github.com/msevestre/CKD-Quakification/blob/main/re_output/Report.md

Section
![image](https://user-images.githubusercontent.com/1041237/165819057-8740d274-52cd-4fd5-a06b-5a771e56d6e2.png)

The table should be a link. How do we do this with the new anchor system? CAn I seen an example somewhere?

**Comment by Yuri05** [comment]
This should be done **automatically by RE**: each figure and each table should become an anchor "figure-NNN" or "table-NNN", where NNN is the number (in the future `<Chapter number>-<table/figure count within main the chapter>` https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/786), e.g.

`**Table 2-1: Hematocrit in Patients With Chronic Kidney Disease<sup>9, 10, 11</sup>** <a id="table-2-1"></a>`

**Comment by msevestre** [comment]
How do we know the number before end? I need to reference the table from a text ? How do I know what the anchor is going to be? I don't quite get it

**Comment by Yuri05** [comment]
OK, what I wrote above was for the dynamically created tables.

But if you are you going to reference a table from the **static content**, then you know excatly the table number and can insert both anchor and reference in the md files.

E.g. in https://github.com/msevestre/CKD-Quakification/blob/main/input/Content/Section2_Model.md 

instead of 
`**Table 1. Hematocrit in Patients With Chronic Kidney Disease<sup>9, 10, 11</sup>**`
must be (also using the new numbering nomenclature)
`**Table 1. Hematocrit in Patients With Chronic Kidney Disease<sup>9, 10, 11</sup>** <a id="table-2-1"></a>`

Unless you insert another tables or put this table in another chapter - the table number 2-1 will not change.
And then you can reference it with `#table-2-1` everywhere.

alternatively you could define an anchor without the table number, e.g.
`**Table 1. Hematocrit in Patients With Chronic Kidney Disease<sup>9, 10, 11</sup>** <a id="table-hct-ckd"></a>`

and then reference it like this
`s. the Table ["Hematocrit in Patients With Chronic Kidney Disease"](#table-hct-ckd)`

Then it does not matter if you insert other tables etc. - the anchor remains valid forever :)
