### ISSUE TITLE
Axis title not centered

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#799]
Is this on purpose?
![image](https://user-images.githubusercontent.com/1041237/165822156-31cd05b3-7b1a-4b6e-9d81-8285e20c0dbf.png)

This looks ugly

**Comment by Yuri05** [comment]
> Is this on purpose?

no :smile: should be centered of course. Bu is the first time I see something like this, in the reports I created before it looked good (e.g. https://github.com/Yuri05/TestReport/blob/main/Report_01/report.md#3-concentration-time-profiles )

**Comment by pchelle** [comment]
This is a side effect of the last `{tlf}` PR that now manages the alignment of each label (as well as font family and face).
Since default value is left align, the RE theme needs to explicitly center them.

**Comment by Yuri05** [comment]
>This is a side effect of the last {tlf} PR that now manages the alignment of each label (as well as font family and face).
Since default value is left align, the RE theme needs to explicitly center them.

I guess that was a misunderstanding between us. When suggesting the default alignment "left", I was talking about the l**egend captions of a plot**, where the default alignment "left" is better than "center".
![grafik](https://user-images.githubusercontent.com/25061876/165917509-6bd2ceb1-1440-46b4-bf6d-028eaf195770.png)

But for axis captions "center" is the better default for sure.

**Comment by pchelle** [comment]
It is actually an omission on my end, I updated the tlf themes to get the best alignments everywhere but forgot to spread the feature to the reporting engine theme.

The issue is the default when the value is not defined in the json theme.
Currently, default undefined fonts in the theme get black color, size of 12 pts, angle of 0 and left alignment

**Comment by msevestre** [comment]
Default should be centered aligned and not left aligned do we agree?

**Comment by Yuri05** [comment]
>Default should be centered aligned and not left aligned do we agree?

yes. Except for the legend captions, where "left" is better.

**Comment by Yuri05** [comment]
>So probably the default when not defined should be changed?

yep. issue created
