### ISSUE TITLE
Range area. Gray color is too gray. This needs to be less in your face by default

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#801]
![image](https://user-images.githubusercontent.com/1041237/165823377-5d4601d9-6665-417a-9f9b-bfc9316ebccd.png)

@pchelle We need a quick turnaround on this. The default gray color is too dark and a sore on the eyes. Can we by default have something else until we actually use a shadded color that matches the main curve with a different hue?

**Comment by pchelle** [comment]
In the configuration plans I have looked at, the color was actually defined as "#000000" ie black
Thus, the area is black with default transparency that ends up being an ugly gray. 

There would 2 possible turnarounds for this:
- increase transparency more to match the gray of PK Sim
- map some area colors to fill colors

I am in favor of the first solution (actually the PK sim plot seems to have a high transparency since we can clearly see the axes lines behind).
Below is a map of black areas with a gradient of transparency values, the current RE transparency is `alpha=0.5`, setting a default to 0.2 or 0.25 should lead to something closer to what PK Sim displays.

![image](https://user-images.githubusercontent.com/45343665/165908005-1995e4f1-abed-46c0-bf73-b50a40d211e8.png)

**Comment by Yuri05** [comment]
>I am in favor of the first solution (actually the PK sim plot seems to have a high transparency since we can clearly see the axes lines behind).

Same for me. Adjusting transparance seems the better (and more generic) solution than manipulating colors.
