### ISSUE TITLE
Malformed articles on the website

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#916]
Some articles are clearly not following Boostrap 5 templates and also TOC contents are incorrect. I am not sure, but `reportOutputStyle.css` might be the culprit here.

![Screenshot 2022-08-15 134638](https://user-images.githubusercontent.com/11330453/184629882-fcbcc507-4a9d-4bc1-b099-24902ad75fea.png)
![Screenshot 2022-08-15 134613](https://user-images.githubusercontent.com/11330453/184629888-499a6d9e-b5f6-44a5-8bac-821fceaa209d.png)
![Screenshot 2022-08-15 134539](https://user-images.githubusercontent.com/11330453/184629891-d68dcb40-aa39-4335-96a0-bea6a7876301.png)

**Comment by Yuri05** [comment]
The problem is that those vignettes include example reports which are in fact standalone markdowns embedded into the vignette  (@pchelle can explain it in more detail)
The CSS ensures that those embedded markdowns become a different background and a border, so that the user can clearly distinguish between the example output and the rest of the vignette.

In a html vignette it's ok, on the website however the level 1 headers are inserted into the navigation panel, which is for sure not optimal. @IndrajeetPatil Is _this_ what you mean with "malformed" - or also something else?

Don't know how to solve though. Maybe @pchelle has an idea.
![grafik](https://user-images.githubusercontent.com/25061876/184632290-9821dffe-3589-47ea-be41-1272434ab2a4.png)

**Comment by IndrajeetPatil** [comment]
> Don't know how to solve though. 

You can just set `toc` value to `1` in YAML for the `.Rmd` doc, and it will suppress those contents.

Another issue is the messy navigation bar at top and the awkward empty space between the navbar and the content.

![image](https://user-images.githubusercontent.com/11330453/184634168-bc0d5dc0-bf7b-4cfd-8129-8bde0e741276.png)

Compare how this looks with how it looks on another [article](https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/articles/qualification-workflow.html) from the same website:

![image](https://user-images.githubusercontent.com/11330453/184634571-247fdcff-4ed9-4f4a-95d7-51832ef39853.png)

**Comment by Yuri05** [comment]
>You can just set toc_depth value to 1 in YAML for the .Rmd doc, and it will suppress those contents.

The problematic headers are all level 1, so they will probably not disappear...

On the other side, we will loose many toc entries which we probably still want to see (compare below original vignette vs depth 1 vigntette)

<img width="350" src="https://user-images.githubusercontent.com/25061876/184640597-d0d9a43c-835c-4340-8020-07334168a5ca.png"> vs. <img width="350" src="https://user-images.githubusercontent.com/25061876/184640651-32416a3c-c094-4344-946d-5dad3ed581cb.png">

By the way, it seems that the website includes only level 1 headers into the navigation sidebar anyway, because level 2/3 headings are not shown there

**Comment by pchelle** [comment]
I think I found the solution, we need to wrap the reports by by an `<object>` tag that aims at embedding html content.
This way the html content is excluded from the generation of the TOC

**Comment by pchelle** [comment]
Then, I need to check if the css style can still be included or if it needs to be defined as a plain style inside the div tag

**Comment by pchelle** [comment]
Additionally, I would like to include the `<details>` tag to fold and unfold the code and its report.
This would aim at having a much clearer view in the vignette and website (s. PR #854 for an example)

**Comment by IndrajeetPatil** [comment]
Not sure if this is supported for the vignettes output, but there is already `code_folding` option for this:
https://bookdown.org/yihui/rmarkdown-cookbook/fold-show.html

**Comment by pchelle** [comment]
I have tried before, it is not supported for vignettes unfortunately.

**Comment by IndrajeetPatil** [comment]
Are you sure about that? I just tried, and it worked for me for `html_vignette` output format.

**Comment by pchelle** [comment]
> Are you sure about that? I just tried, and it worked for me for `html_vignette` output format.

You are right ! It works now. Thanks

**Comment by Yuri05** [comment]
hopefully it would also fix https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/711 (which was closed, but still an issue)

**Comment by pchelle** [comment]
After some investigation, the issue was actually that the rendered reports included styling that was messing up the general style.
Rendering with `html_fragment()` could have worked but images were weirdly displayed and embedding with `<object>` worked for regular knitting of the vignette but not with `{pkgdown}` that is still fetching the report titles.

Thus, the best workaround I have found so far is to include the report as an image file with the following process (PR #917 ):

- Add styling tags to the markdown report prior rendering
- Rendering the report in `html` with the associated style different from vignette/article
- Convert the rendered report as a png file using the package `{webshot}`
- Display the image of the report in the article
