### ISSUE TITLE
Report folder does not content images references by the md

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#955]
I am sure there is a way to make it work. For now, the images references statically are not copied in the report folder
![image](https://user-images.githubusercontent.com/1041237/202750884-09b729ea-8082-4b37-9f3d-9a807f420e8d.png)

So it looks like the image is missing

https://github.com/Open-Systems-Pharmacology/Qualification-CKD/blob/952e1fbc9da1428ccd7c0bfb855c6117efc08efe/Qualification/report/report.md

How do I make this work? I know there are some instructions regarding files to be copied. How does this work again?

@pchelle @Yuri05

**Comment by Yuri05** [comment]
as far as I remember, eveything under `Content/images` is automatically copied under `<report-folder>/images` https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/618
Can you see those images under `re_input/Content/images`?

**Comment by msevestre** [comment]
Yes they are. Just not on the report folder. I think it's a bug

**Comment by Yuri05** [comment]
Yep, seems to be s Bug. 
@pchelle can you check please?

**Comment by pchelle** [comment]
The issue is that there are brackets `(...)` within the file name of the figure link/path.
When copying the report and its figures, the algorithm I implemented 

1- finds lines where the characters `![` are found
2- removes everything until `](` and everything after the next `)` to get the figure path
3- copy the figure path in the new folder

Here the figure path is truncated due to the brackets within the link and the corresponding path does not exist.
